services:
  - type: web
    name: wpp-pfp-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 